// =============================================================================
// MASTER CONFIG  (config.master.js)  —  THE single place to edit shared values
// =============================================================================
// Edit values HERE. Then run `npm run config:gen` (or just build / deploy — it
// runs automatically). The generator (scripts/gen-config.js) expands this file
// into the three per-runtime configs that actually ship:
//
//   • functions/api/config.js     — backend (Catalyst function bundle)
//   • client/src/config.js        — React app (webpack bundle)
//   • client/public/landing.html  — static marketing page (CONFIG block)
//
// WHY THREE OUTPUT FILES (and not one shared import): Catalyst deploys the
// backend and the client as SEPARATE bundles, and the landing page is plain
// static HTML. None of them can import a common module at runtime. So we keep
// ONE editable source (this file) and generate the three at build time. Those
// generated files carry a "DO NOT EDIT" header — change them here instead.
//
// SECRETS DO NOT BELONG HERE. CRON_SECRET / VAPID keys stay in
// functions/api/catalyst-config.json (gitignored) and are read via process.env.
// Backend values below may still be overridden per-deploy by env vars — the
// generator preserves the `process.env.X || <default>` pattern using these as
// the defaults.
// =============================================================================

module.exports = {
  // ---- Shared everywhere (backend + client + landing) ----------------------
  shared: {
    brandName:          'VidyaSetu',          // platform fallback name
    supportEmail:       'support@veena.app',
    supportPhoneTel:    '+919360390883',      // digits for tel: hrefs
    supportPhoneDisplay:'+91 93603 90883',    // what users see
    countryCode:        '91',                 // WhatsApp / phone normalization
    locale:             'en-IN',
    currency:           'INR',
    currencySymbol:     '₹',             // the rupee symbol
  },

  // ---- Pricing (landing-page display copy only — billing is not wired) -----
  // Model: a flat monthly BASE that already includes `included` students, then
  // a per-student rate for each student beyond that. `base`/`perStudent` are the
  // LIVE launch prices; `baseRegular`/`perStudentRegular` are the higher
  // struck-through anchors. Set a *Regular to null (or equal to live) to drop
  // its strike. This object is the single source for every price + the
  // estimator on client/public/landing.html.
  prices: {
    // Promotion pill above the pricing heading. '' hides the pill and presents
    // prices as the standard rate with no offer framing.
    offerName: 'Limited-time launch offer · introductory pricing',
    core: {
      base: 1000, baseRegular: 1500,        // ₹/month, includes `included` students
      included: 15,
      perStudent: 50, perStudentRegular: 75, // ₹/student/month beyond `included`
    },
    complete: {
      base: 2000, baseRegular: 2999,
      included: 15,
      perStudent: 90, perStudentRegular: 130,
    },
    // Student counts shown as example totals in the pricing comparison table.
    sampleCounts: [15, 30, 60],
  },

  // ---- Feature catalog (single source of truth) ----------------------------
  // One list drives BOTH the pricing comparison sheet (pricing.html matrix,
  // generated by gen-config.js) AND the app's plan gating. Each item:
  //   { label, core: bool, complete: bool, gate? }
  // `core`/`complete` decide the check/dash in the matrix. `gate` (optional)
  // ties the row to a capability the app actually enforces server-side:
  //   'lessons' | 'assignments' | 'question_papers'  → premium MODULE keys
  //       (gen-config emits these into PREMIUM_MODULES; plans.js reads it, so
  //        moving one of these between plans changes what the app unlocks).
  //   'detailed_reports'  → a plan-tier check (reports.js requireComplete),
  //       not a module toggle, so it is documented here but enforced directly.
  // Rows WITHOUT a gate are descriptive: they ride inside a module and only
  // affect the sheet. To make a brand-new row enforceable, add a matching code
  // hook and reuse/extend a gate value here.
  // Each item has a stable `key` (referenced by code hooks: requireFeature on
  // the server, featureOn in the client). `core`/`complete` drive BOTH the
  // matrix and the live gate. Optional `gate` keeps the legacy module mapping
  // for PREMIUM_MODULES. `enforce` records where the switch actually bites:
  //   'module'  — the feature's whole API route group is gated (requireFeature)
  //   'inline'  — a specific endpoint / UI element is gated
  //   'client'  — UI-only (no server endpoint to gate; hidden when off)
  //   'inherent'— platform behavior that cannot be switched off (always on)
  features: {
    categories: [
      { name: 'Students & Attendance', items: [
        { key: 'students.profiles',   label: 'Student profiles & full history', core: true, complete: true, enforce: 'module' },
        { key: 'students.contacts',   label: 'Parent contacts (kept private)',  core: true, complete: true, enforce: 'inherent' },
        { key: 'students.photos',     label: 'Student photos',                  core: true, complete: true, enforce: 'client' },
        { key: 'groups.batches',      label: 'Groups & batches',                core: true, complete: true, enforce: 'module' },
        { key: 'students.import',     label: 'Bulk CSV import',                 core: true, complete: true, enforce: 'inline' },
        { key: 'attendance.daily',    label: 'One-tap daily attendance',        core: true, complete: true, enforce: 'module' },
        { key: 'attendance.rosters',  label: 'Auto-built class rosters',        core: true, complete: true, enforce: 'inherent' },
      ] },
      { name: 'Fees & Payments', items: [
        { key: 'fees.tracking',     label: 'Fee tracking & dues',             core: true, complete: true, enforce: 'module' },
        { key: 'fees.perStudent',   label: 'Per-student fee plans',           core: true, complete: true, enforce: 'client' },
        { key: 'fees.additional',   label: 'Additional charges & discounts',  core: true, complete: true, enforce: 'inline' },
        { key: 'fees.reminders',    label: 'Automatic monthly reminders',     core: true, complete: true, enforce: 'inline' },
        { key: 'fees.statements',   label: 'Monthly statements per student',  core: true, complete: true, enforce: 'inherent' },
        { key: 'fees.upi_qr',       label: 'UPI & pay-by-QR collection',      core: true, complete: true, enforce: 'inline' },
      ] },
      { name: 'Classes & Scheduling', items: [
        { key: 'classes.timetable',  label: 'Weekly timetable grid',                 core: true, complete: true, enforce: 'module' },
        { key: 'classes.types',      label: 'Online, in-person & group classes',     core: true, complete: true, enforce: 'inherent' },
        { key: 'classes.join_links', label: 'One-tap join links for online classes', core: true, complete: true, enforce: 'inline' },
        { key: 'classes.exceptions', label: 'Reschedule or cancel a single date',    core: true, complete: true, enforce: 'inline' },
      ] },
      { name: 'Camps & Workshops', items: [
        { key: 'camps.run',       label: 'Short-term camps & intensives',   core: true, complete: true, enforce: 'module' },
        { key: 'camps.roster',    label: 'Own dates, roster & attendance',  core: true, complete: true, enforce: 'inherent' },
      ] },
      { name: 'Communication & Notifications', items: [
        { key: 'messages.send',      label: 'WhatsApp & in-app messaging',     core: true, complete: true, enforce: 'module' },
        { key: 'messages.bulk',      label: 'Bulk "Send all" messages',        core: true, complete: true, enforce: 'client' },
        { key: 'messages.templates', label: 'Editable message templates',      core: true, complete: true, enforce: 'inline' },
        { key: 'notify.auto',        label: 'Absence alerts & fee reminders',  core: true, complete: true, enforce: 'inherent' },
        { key: 'notify.bell',        label: 'In-app notification bell',        core: true, complete: true, enforce: 'client' },
        { key: 'notify.push',        label: 'Web-push to the lock screen',     core: true, complete: true, enforce: 'inline' },
        { key: 'notify.digest',      label: 'Automatic morning class digest',  core: true, complete: true, enforce: 'inherent' },
      ] },
      { name: 'Parent Portal', items: [
        { key: 'portal.login',     label: 'Secure per-family login',         core: true,  complete: true, enforce: 'inherent' },
        { key: 'portal.glance',    label: 'Attendance & fees at a glance',    core: true,  complete: true, enforce: 'inherent' },
        { key: 'portal.profile',   label: 'Profile self-service',            core: true,  complete: true, enforce: 'inline' },
        { key: 'portal.learning',  label: 'Lessons & assignments view',      core: false, complete: true, gate: 'lessons', enforce: 'module' },
      ] },
      { name: 'Lessons & Courses', items: [
        { key: 'lessons.build',     label: 'Build video courses',             core: false, complete: true, gate: 'lessons', enforce: 'module' },
        { key: 'lessons.player',    label: 'Distraction-free lesson player',  core: false, complete: true, gate: 'lessons', enforce: 'module' },
        { key: 'lessons.resources', label: 'Notes & resources per lesson',    core: false, complete: true, gate: 'lessons', enforce: 'module' },
        { key: 'lessons.progress',  label: 'Per-student progress tracking',   core: false, complete: true, gate: 'lessons', enforce: 'module' },
        { key: 'lessons.enrol',     label: 'One-click course enrolment',      core: false, complete: true, gate: 'lessons', enforce: 'module' },
      ] },
      { name: 'Quizzes & Certificates', items: [
        { key: 'quizzes.add',       label: 'Add quizzes to lessons',              core: false, complete: true, gate: 'lessons', enforce: 'module' },
        { key: 'quizzes.gate',      label: 'Gate course completion on quizzes',   core: false, complete: true, gate: 'lessons', enforce: 'module' },
        { key: 'quizzes.certs',     label: 'Auto-issued completion certificates', core: false, complete: true, gate: 'lessons', enforce: 'module' },
      ] },
      { name: 'Assignments', items: [
        { key: 'assignments.assign', label: 'Assign work to students or batches',  core: false, complete: true, gate: 'assignments', enforce: 'module' },
        { key: 'assignments.due',    label: 'Families see what is due',            core: false, complete: true, gate: 'assignments', enforce: 'module' },
        { key: 'assignments.notify', label: 'Notifications on new assignments',    core: false, complete: true, gate: 'assignments', enforce: 'module' },
      ] },
      { name: 'Question Papers', items: [
        { key: 'papers.share',  label: 'Share practice papers to the portal', core: false, complete: true, gate: 'question_papers', enforce: 'module' },
        { key: 'papers.prep',   label: 'Students prepare any time',           core: false, complete: true, gate: 'question_papers', enforce: 'module' },
      ] },
      { name: 'Reports', items: [
        { key: 'reports.basic',     label: 'Attendance & fee summaries',  core: true,  complete: true, enforce: 'module' },
        { key: 'reports.detailed',  label: 'Detailed reports & trends',   core: false, complete: true, gate: 'detailed_reports', enforce: 'inline' },
        { key: 'reports.lessons',   label: 'Lesson activity reports',     core: false, complete: true, gate: 'lessons', enforce: 'inline' },
      ] },
      { name: 'Mobile & PWA', items: [
        { key: 'pwa.install',   label: 'Installable mobile app (PWA)',                core: true, complete: true, enforce: 'inherent' },
        { key: 'pwa.a2hs',      label: 'Add to home screen on Android & iPhone',      core: true, complete: true, enforce: 'inherent' },
        { key: 'pwa.theme',     label: 'Dark mode & brand themes',                    core: true, complete: true, enforce: 'inherent' },
      ] },
      { name: 'Multi-academy & Data', items: [
        { key: 'multi.branches', label: 'Run multiple branches from one login', core: true, complete: true, enforce: 'inherent' },
        { key: 'multi.isolated', label: 'Isolated, private data per academy',   core: true, complete: true, enforce: 'inherent' },
        { key: 'data.export',    label: 'Data export & backup',                 core: true, complete: true, enforce: 'inline' },
      ] },
      { name: 'Support', items: [
        { key: 'support.setup',  label: 'Guided setup & walkthrough',  core: true, complete: true, enforce: 'inherent' },
        { key: 'support.human',  label: 'Real human support',          core: true, complete: true, enforce: 'inherent' },
      ] },
    ],
  },

  // ---- Backend-only (functions/api/config.js) ------------------------------
  backend: {
    photoBucket:        'student-photos-profile', // Stratus bucket name
    photoMaxRawBytes:   8 * 1024 * 1024,          // 8 MB pre-resize
    photoSignedUrlTtl:  '3600',                   // seconds (string for SDK)
    imageMaxDimension:  800,                       // px, longest side
    imageJpegQuality:   85,                        // 0-100
    jsonBodyLimit:      '10mb',                     // express.json limit
    zcqlPageSize:       300,                         // hard platform cap
    quizPassThreshold:  70,                          // percent to pass a quiz
    platformAdminRole:  'App Administrator',         // Catalyst role string
  },
};
