-- ============================================================================
-- VidyaSetu / Veena — Postgres schema (Supabase migration from Zoho Catalyst)
-- ============================================================================
-- Generated for the Catalyst -> Supabase migration. One table per Catalyst
-- Data Store table. Conventions:
--
--   * Table names are the LOWERCASE of the Catalyst name (Students -> students,
--     ClassStudents -> classstudents). Postgres folds unquoted identifiers to
--     lowercase, so the app's existing `SELECT ... FROM Students` resolves to
--     `students` with no query rewriting.
--   * id            -> Catalyst ROWID (17-digit). bigint PK, GENERATED BY
--                      DEFAULT AS IDENTITY so data-migration can INSERT the old
--                      ROWID explicitly, while brand-new rows auto-generate an
--                      id (small ints; never collide with 17-digit migrated ids).
--   * created_at    -> Catalyst CREATEDTIME.  updated_at -> MODIFIEDTIME.
--   * org_id        -> tenant scope (bigint). Present on every tenant table.
--                      Absent on organizations (root), leads + auditlog +
--                      platformconfig (platform-level).
--   * source_id     -> nullable bigint on every MIGRATED table; stores the old
--                      Catalyst ROWID so child FKs can be re-linked on import.
--   * Date/time values were stored as TEXT strings in Catalyst (YYYY-MM-DD,
--     HH:MM, ISO) and are kept as text here for a faithful port.
--   * ROWID references (*_id) are bigint (17-digit, exceed JS int range).
--   * JSON-bearing columns (classes.exceptions, lessonquizzes.options,
--     platformconfig.config_json, auditlog.detail, appsettings.setting_value)
--     are TEXT, not jsonb, ON PURPOSE. The app stringifies on write and
--     JSON.parse()s on read; a real jsonb column would be auto-parsed to an
--     object by the pg driver, double-parsing and silently dropping the data.
--     setting_value also holds plain (non-JSON) strings that jsonb would reject.
--
-- FK constraints are intentionally NOT enforced in v1 (Catalyst had none, the
-- app enforces integrity at the app layer, and the importer tolerates orphaned
-- optional links). Indexes ARE created. FKs can be added post-migration.
-- ============================================================================

-- ------------------------------------------------------------------ tenancy
create table if not exists organizations (        -- Organizations (tenant root; no org_id)
  id             bigint generated by default as identity primary key,
  name           text not null,
  slug           text,
  owner_user_id  bigint,
  status         text default 'active',
  plan           text default 'trial',
  logo_url       text default '',
  source_id      bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);
create index if not exists idx_orgs_slug on organizations (slug);

create table if not exists orgmemberships (        -- OrgMemberships
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  user_id     bigint not null,
  role        text default 'teacher',              -- owner | teacher
  status      text default 'invited',              -- invited | active | removed
  source_id   bigint,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);
create index if not exists idx_memberships_org on orgmemberships (org_id);
create index if not exists idx_memberships_user on orgmemberships (user_id);

-- ------------------------------------------------------- level 0: roots
create table if not exists students (              -- Students
  id                     bigint generated by default as identity primary key,
  org_id                 bigint not null,
  name                   text not null,
  parent_name            text,
  mobile_number          text,
  fee_online             numeric default 0,
  fee_offline            numeric default 0,
  fee_offline_group      numeric default 0,
  min_classes_per_month  integer default 0,
  monthly_fee            numeric default 0,
  status                 text default 'active',
  notes                  text default '',
  date_of_birth          text,                     -- YYYY-MM-DD, nullable
  email                  text default '',
  address                text default '',
  father_name            text default '',
  mother_name            text default '',
  photo_url              text default '',          -- storage object key
  login_email            text default '',          -- parent-login fields (on-row)
  login_user_id          bigint,                   -- Supabase auth user id (was Catalyst user)
  login_status           text default '',
  source_id              bigint,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz
);
create index if not exists idx_students_org on students (org_id);
create index if not exists idx_students_org_src on students (org_id, source_id);
create index if not exists idx_students_login_email on students (login_email);

create table if not exists groups (                -- Groups / Batches
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  name         text not null,
  description  text default '',
  status       text default 'active',
  source_id    bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);
create index if not exists idx_groups_org on groups (org_id);
create index if not exists idx_groups_org_src on groups (org_id, source_id);

create table if not exists courses (               -- Courses
  id             bigint generated by default as identity primary key,
  org_id         bigint not null,
  name           text not null,
  description    text default '',
  thumbnail_url  text default '',
  status         text default 'active',            -- active | archived
  source_id      bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);
create index if not exists idx_courses_org on courses (org_id);
create index if not exists idx_courses_org_src on courses (org_id, source_id);

create table if not exists questionpapers (        -- QuestionPapers
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  title        text not null,
  description  text default '',
  link         text not null,
  category     text default '',
  source_id    bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);
create index if not exists idx_qpapers_org on questionpapers (org_id);
create index if not exists idx_qpapers_org_src on questionpapers (org_id, source_id);

create table if not exists appsettings (           -- AppSettings (key/value; upsert on natural key)
  id             bigint generated by default as identity primary key,
  org_id         bigint not null,
  setting_key    text not null,                    -- dotted namespace, e.g. billing.fee_mode
  setting_value  text,                             -- plain / 'true' / int / JSON string
  created_at     timestamptz not null default now(),
  updated_at     timestamptz,
  unique (org_id, setting_key)
);

-- ------------------------------------------------- level 1: depend on roots
create table if not exists camps (                 -- Camps
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  name         text not null,
  group_id     bigint,                             -- optional context
  start_date   text,                               -- YYYY-MM-DD
  end_date     text,
  total_days   integer default 0,
  daily_fee    numeric default 0,
  status       text default 'active',
  notes        text default '',
  source_id    bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);
create index if not exists idx_camps_org on camps (org_id);
create index if not exists idx_camps_org_src on camps (org_id, source_id);

create table if not exists lessons (               -- Lessons
  id                bigint generated by default as identity primary key,
  org_id            bigint not null,
  course_id         bigint,
  title             text not null,
  description       text default '',
  video_url         text default '',
  content_url       text default '',
  content_type      text default 'video',          -- video | document | quiz
  duration_seconds  integer default 0,
  order_index       integer default 0,
  section_name      text default '',
  start_seconds     integer default 0,
  end_seconds       integer default 0,
  quiz_required     boolean default false,
  quiz_shuffle      boolean default false,
  source_id         bigint,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);
create index if not exists idx_lessons_org on lessons (org_id);
create index if not exists idx_lessons_course on lessons (course_id);
create index if not exists idx_lessons_org_src on lessons (org_id, source_id);

create table if not exists groupstudents (         -- GroupStudents (M2M)
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  group_id    bigint not null,
  student_id  bigint not null,
  source_id   bigint,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);
create index if not exists idx_groupstudents_org on groupstudents (org_id);
create index if not exists idx_groupstudents_group on groupstudents (group_id);
create index if not exists idx_groupstudents_student on groupstudents (student_id);
create index if not exists idx_groupstudents_org_src on groupstudents (org_id, source_id);

create table if not exists classes (               -- Classes / Timetable
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  name            text not null,
  group_id        bigint,                          -- nullable (group class)
  student_id      bigint,                          -- nullable (legacy 1-on-1)
  class_type      text not null,                   -- online|offline|offline_group|online_group
  day_of_week     integer,                         -- 0-6 (Sun-Sat)
  start_time      text,                            -- HH:MM
  end_time        text,
  duration_hours  numeric default 1,
  is_active       integer default 1,               -- stored 0/1 (kept faithful)
  meeting_link    text default '',
  exceptions      text,                             -- JSON array (string; app parses)
  source_id       bigint,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_classes_org on classes (org_id);
create index if not exists idx_classes_group on classes (group_id);
create index if not exists idx_classes_student on classes (student_id);
create index if not exists idx_classes_org_src on classes (org_id, source_id);

create table if not exists courseenrollments (     -- CourseEnrollments
  id               bigint generated by default as identity primary key,
  org_id           bigint not null,
  course_id        bigint not null,
  student_id       bigint not null,
  status           text default 'active',
  completed_count  integer default 0,
  completed        boolean default false,
  completed_at     text,                            -- ISO string, locked once
  source_id        bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz
);
create index if not exists idx_enroll_org on courseenrollments (org_id);
create index if not exists idx_enroll_course on courseenrollments (course_id);
create index if not exists idx_enroll_student on courseenrollments (student_id);
create index if not exists idx_enroll_org_src on courseenrollments (org_id, source_id);

-- ------------------------------------------------ level 2: depend on level 1
create table if not exists classstudents (         -- ClassStudents (M2M roster)
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  class_id    bigint not null,
  student_id  bigint not null,
  source_id   bigint,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);
create index if not exists idx_classstudents_org on classstudents (org_id);
create index if not exists idx_classstudents_class on classstudents (class_id);
create index if not exists idx_classstudents_student on classstudents (student_id);
create index if not exists idx_classstudents_org_src on classstudents (org_id, source_id);

create table if not exists campdays (              -- CampDays
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  camp_id         bigint not null,
  day_date        text,                            -- YYYY-MM-DD
  start_time      text,                            -- HH:MM
  end_time        text,
  class_type      text default 'offline_group',
  duration_hours  numeric default 1,
  status          text default 'active',           -- active | cancelled
  source_id       bigint,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_campdays_org on campdays (org_id);
create index if not exists idx_campdays_camp on campdays (camp_id);
create index if not exists idx_campdays_org_src on campdays (org_id, source_id);

create table if not exists lessonquizzes (         -- LessonQuizzes (one row per MCQ)
  id             bigint generated by default as identity primary key,
  org_id         bigint not null,
  lesson_id      bigint not null,
  question       text,
  options        text,                             -- JSON array (string; app parses)
  correct_index  integer default 0,
  explanation    text default '',
  order_index    integer default 0,
  source_id      bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);
create index if not exists idx_lessonquizzes_org on lessonquizzes (org_id);
create index if not exists idx_lessonquizzes_lesson on lessonquizzes (lesson_id);
create index if not exists idx_lessonquizzes_org_src on lessonquizzes (org_id, source_id);

create table if not exists assignments (           -- Assignments
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  title           text not null,
  instructions    text default '',
  link            text default '',
  due_date        text default '',                 -- YYYY-MM-DD
  kind            text default 'task',             -- task | quiz
  quiz_lesson_id  bigint,                          -- nullable (kind=quiz)
  target_type     text default 'all',              -- all | group | student
  target_id       bigint,                          -- polymorphic (group/student), nullable
  source_id       bigint,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_assignments_org on assignments (org_id);
create index if not exists idx_assignments_org_src on assignments (org_id, source_id);

-- ------------------------------------------ level 3: activity / history
create table if not exists attendance (            -- Attendance
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  student_id      bigint not null,                 -- row owner
  class_id        bigint,                          -- nullable (adhoc/camp)
  camp_id         bigint,                          -- nullable (camp attendance)
  class_date      text not null,                   -- YYYY-MM-DD (client alias: date)
  status          text not null,                   -- present | absent | late
  class_type      text default 'offline',
  duration_hours  numeric default 1,
  fee_charged     numeric default 0,
  topic           text default '',
  notes           text default '',
  recording_url   text default '',
  source_id       bigint,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_attendance_org on attendance (org_id);
create index if not exists idx_attendance_student on attendance (student_id);
create index if not exists idx_attendance_class on attendance (class_id);
create index if not exists idx_attendance_date on attendance (class_date);
create index if not exists idx_attendance_org_src on attendance (org_id, source_id);

create table if not exists additionalfees (        -- AdditionalFees
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  student_id   bigint not null,
  description  text,
  amount       numeric,                             -- may be negative (discount)
  fee_date     text,                                -- YYYY-MM-DD (client alias: date)
  fee_month    integer,                             -- 1-12 (client alias: month)
  fee_year     integer,                             -- (client alias: year)
  source_id    bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);
create index if not exists idx_addfees_org on additionalfees (org_id);
create index if not exists idx_addfees_student on additionalfees (student_id);
create index if not exists idx_addfees_org_src on additionalfees (org_id, source_id);

create table if not exists payments (              -- Payments
  id            bigint generated by default as identity primary key,
  org_id        bigint not null,
  student_id    bigint not null,
  fee_month     integer,                            -- 1-12
  fee_year      integer,
  paid_amount   numeric,
  payment_date  text,                               -- YYYY-MM-DD
  notes         text default '',
  source_id     bigint,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz
);
create index if not exists idx_payments_org on payments (org_id);
create index if not exists idx_payments_student on payments (student_id);
create index if not exists idx_payments_org_src on payments (org_id, source_id);

create table if not exists messages (              -- Messages (draft parent messages)
  id             bigint generated by default as identity primary key,
  org_id         bigint not null,
  student_id     bigint,                            -- nullable (custom message)
  parent_name    text default '',
  mobile_number  text default '',
  message        text,
  message_type   text default 'custom',
  is_sent        integer default 0,                 -- stored 0/1
  source_id      bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);
create index if not exists idx_messages_org on messages (org_id);
create index if not exists idx_messages_student on messages (student_id);
create index if not exists idx_messages_org_src on messages (org_id, source_id);

create table if not exists lessonprogress (        -- LessonProgress
  id                bigint generated by default as identity primary key,
  org_id            bigint not null,
  student_id        bigint not null,
  lesson_id         bigint not null,
  watched_seconds   integer default 0,
  duration_seconds  integer default 0,
  percent_complete  integer default 0,
  completed         boolean default false,
  source_id         bigint,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);
create index if not exists idx_progress_org on lessonprogress (org_id);
create index if not exists idx_progress_student on lessonprogress (student_id);
create index if not exists idx_progress_lesson on lessonprogress (lesson_id);
create index if not exists idx_progress_org_src on lessonprogress (org_id, source_id);

create table if not exists quizattempts (          -- QuizAttempts
  id               bigint generated by default as identity primary key,
  org_id           bigint not null,
  student_id       bigint not null,
  lesson_id        bigint not null,
  score            integer default 0,               -- percent
  total_questions  integer default 0,
  correct_count    integer default 0,
  attempts         integer default 0,
  passed           boolean default false,
  source_id        bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz
);
create index if not exists idx_attempts_org on quizattempts (org_id);
create index if not exists idx_attempts_student on quizattempts (student_id);
create index if not exists idx_attempts_lesson on quizattempts (lesson_id);
create index if not exists idx_attempts_org_src on quizattempts (org_id, source_id);

create table if not exists assignmentcompletions ( -- AssignmentCompletions
  id             bigint generated by default as identity primary key,
  org_id         bigint not null,
  assignment_id  bigint not null,
  student_id     bigint not null,
  source_id      bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);
create index if not exists idx_acompletions_org on assignmentcompletions (org_id);
create index if not exists idx_acompletions_assignment on assignmentcompletions (assignment_id);
create index if not exists idx_acompletions_student on assignmentcompletions (student_id);
create index if not exists idx_acompletions_org_src on assignmentcompletions (org_id, source_id);

-- ------------------------------------------------ notifications (not migrated)
create table if not exists notifications (         -- Notifications (in-app bell)
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  student_id      bigint default 0,                 -- parent inbox; 0 for admin/org rows
  recipient_role  text,                             -- parent | admin (nullable legacy)
  type            text default 'general',
  title           text,
  body            text,
  link            text default '',
  is_read         boolean default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_notifications_org on notifications (org_id);
create index if not exists idx_notifications_student on notifications (student_id);

create table if not exists pushsubscriptions (     -- PushSubscriptions (web-push)
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  student_id      bigint,                            -- device owner (parent) / admin id
  recipient_role  text,                              -- admin for teacher devices
  endpoint        text,
  p256dh          text,
  auth            text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_pushsubs_org on pushsubscriptions (org_id);
create index if not exists idx_pushsubs_student on pushsubscriptions (student_id);

create table if not exists messagetemplates (      -- MessageTemplates
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  type        text not null,                        -- absence_alert | fee_reminder | ...
  body        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  unique (org_id, type)
);

-- ------------------------------------------------ platform-level (no org_id)
create table if not exists leads (                 -- Leads (landing-page contact form)
  id             bigint generated by default as identity primary key,
  name           text not null,
  email          text not null,
  phone          text not null,
  academy_type   text default 'Other',
  academy_name   text default '',
  student_count  text default '',                   -- free-form band (text, not int)
  city           text default '',
  message        text default '',
  source         text default 'landing',
  status         text default 'new',
  notes          text default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);

create table if not exists invoices (              -- Invoices (platform billing ledger)
  id         bigint generated by default as identity primary key,
  org_id     bigint not null,                       -- academy billed
  amount     numeric default 0,
  period     text,                                  -- e.g. "Jun 2026"
  status     text default 'pending',                -- pending | paid | void
  due_date   text,
  paid_at    text default '',
  notes      text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
create index if not exists idx_invoices_org on invoices (org_id);

create table if not exists auditlog (              -- AuditLog (platform-admin trail; append-only)
  id               bigint generated by default as identity primary key,
  actor_user_id    text,
  actor_email      text,
  action           text,                            -- e.g. org.suspend
  target_org_id    bigint,                          -- nullable
  target_org_name  text,
  detail           text,                            -- JSON string (kept as text)
  created_at       timestamptz not null default now()
);
create index if not exists idx_auditlog_target on auditlog (target_org_id);

create table if not exists platformconfig (        -- PlatformConfig (global singleton config)
  id           bigint generated by default as identity primary key,
  config_key   text not null unique,                -- e.g. 'pricing'
  config_json  text,                                 -- JSON object (string; app parses)
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);
